server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/hhtqaq/demo-springcloud/
            search-paths: spring_cloud_in_action/config-repo
            username: 1293115411@qq.com
            password: Ire7758521
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/